all:
	mpicxx -O3 ./mpi_matrices_blocking.cpp -o mpi_matrices_blocking
	mpicxx -O3 ./mpi_matrices_non_blocking.cpp -o mpi_matrices_non_blocking
	g++ -O3 ./mpi_matrices_serial.cpp -o mpi_matrices_serial